name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  #Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: third_party/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: third_party/fonts/Raleway-Light.ttf
          weight: 300
        - asset: third_party/fonts/Raleway-Regular.ttf
        - asset: third_party/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: third_party/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: third_party/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: third_party/fonts/Raleway-Black.ttf
          weight: 900
        - asset: third_party/fonts/Raleway-Italic.ttf
          style: italic


    - family:  Flutter_Clock
      fonts:
        - asset: third_party/icons/Flutter_Clock.ttf